spring:
  application:
    name: pc-auth-ms
  profiles:
    active: dev
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:18888}"

server:
  port: 8087

jwt:
  secret: ${JWT_SECRET:}
  expiration: 86400000