server:
  port: 28080

spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: pc-catalogo-categorias
              uri: lb://PC-CATALOGO-MS
              predicates:
                - Path=/api/v1/categorias/**
            - id: pc-catalogo-productos
              uri: lb://PC-CATALOGO-MS
              predicates:
                - Path=/api/v1/productos/**
            - id: pc-orden-ms
              uri: lb://PC-ORDEN-MS
              predicates:
                - Path=/api/v1/ordenes/**
            - id: pc-pago-ms
              uri: lb://PC-PAGO-MS
              predicates:
                - Path=/api/v1/pagos/**
            - id: pc-cotizacion-ms
              uri: lb://PC-COTIZACION-MS
              predicates:
                - Path=/api/v1/cotizaciones/**
            - id: pc-auth-ms
              uri: lb://PC-AUTH-MS
              predicates:
                - Path=/api/v1/auth/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://pc-eureka:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always