spring:
  application:
    name: pc-cotizacion-ms
  profiles:
    active: dev
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:18888}"

server:
  port: 8089

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers
  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://zipkin:9411}/api/v2/spans

logging:
  pattern:
    correlation: "[%X{traceId:-} %X{spanId:-}]"
  level:
    root: INFO
    pe.edu.upeu.eniaclabs: DEBUG