{
 "title": "ENIAC Labs - Infraestructura & Node Exporter",
 "tags": [
  "eniaclabs",
  "node-exporter",
  "system",
  "infrastructure"
 ],
 "time": { "to": "now", "from": "now-15m" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Uso de CPU del Servidor (%)",
   "type": "timeseries",
   "gridPos": { "y": 0, "w": 12, "x": 0, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "legendFormat": "CPU Utilizada: {{instance}}",
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode='idle'}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "Uso de Memoria RAM del Sistema (Bytes)",
   "type": "timeseries",
   "gridPos": { "y": 0, "w": 12, "x": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "legendFormat": "Memoria Usada: {{instance}}",
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes"
    },
    { "legendFormat": "Memoria Total: {{instance}}", "expr": "node_memory_MemTotal_bytes" }
   ]
  },
  {
   "title": "Tráfico de Red I/O (Bytes/s)",
   "type": "timeseries",
   "gridPos": { "y": 8, "w": 12, "x": 0, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "legendFormat": "RX (Entrada): {{instance}}",
     "expr": "sum(rate(node_network_receive_bytes_total[1m])) by (instance)"
    },
    {
     "legendFormat": "TX (Salida): {{instance}}",
     "expr": "sum(rate(node_network_transmit_bytes_total[1m])) by (instance)"
    }
   ]
  },
  {
   "title": "Actividad de Disco I/O (Lectura / Escritura)",
   "type": "timeseries",
   "gridPos": { "y": 8, "w": 12, "x": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "legendFormat": "Read: {{instance}}",
     "expr": "sum(rate(node_disk_read_bytes_total[1m])) by (instance)"
    },
    {
     "legendFormat": "Write: {{instance}}",
     "expr": "sum(rate(node_disk_written_bytes_total[1m])) by (instance)"
    }
   ]
  }
 ]
}